modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "icon.png"

[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "ldlib2"
type = "required"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "viscript_lib"
type = "required"
versionRange = "[${viscriptlib_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "beyonddimensions"
type = "optional"
versionRange = "[0.7.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "jecharacters"
type = "optional"
versionRange = "[4.5.23,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies."${mod_id}"]]
modId = "ftbquests"
type = "optional"
versionRange = "[2101.1.20,)"
ordering = "AFTER"
side = "BOTH"
